### ISSUE TITLE
how would you do the same for a JSON object

### ISSUE THREAD

**Issue by premtemp1** [fandyaditya/semantic-search-langchain#1]
Hello,
 Thanks for the article but most of the info I see is for text file. It would helpful if you can do a JSON version. for example, an array of json object 
[
{
   "name":"xxxx"
   "age":"xxxx
   "address" "xxxxx"
},
{
  "name":"xxxx"
   "age":"xxxx
   "address" "xxxxx"
}
]

**Comment by fandyaditya** [comment]
What i understand you want to do semantic search, but instead via txt file, the input is JSON?

Can you give me more example?

**Comment by premtemp1** [comment]
Thank you for responding...

This is what I was thinking... Suppose you have a list of restaurants information  . Then you can ask a question " find me restaurants that has  mango lassi on the menu" or show restaurant in area code 33333 that has greek food"  .  The output should a list of matches (complete json) and ranking..

The data could be:
```
[
  {
     "name :"rest 1"
     "type":"italian",
     "location":[
        "city":" some city"
        "zip" :"33333"
      ],
     " description":" some description"
     "menu":[
         menu item 1
         menu item 3
     ]
  },
  {
     "name :"rest 2"
     "type":"indian",
     "loacation":[
        "city":" some city"
        "zip" :"33333"
      ],
     " description":" some description"
     "menu":[
         menu item 1
         menu item 3
     ]
  }
.....
]
```
Then imagine, someone can create a chatbot and enter the question and that pass to LLM service and return the info to the user with link
Thanks for your time .

**Comment by fandyaditya** [comment]
Ahh I see, yes I think this is also possible in with this approach:

First:
You give the LMM input based on user chat and instruct the LMM to translate the user input into JSON.
eg: 

`Based on this input, please convert it into JSON:
input: ${userInput}`

And when the LMM returns the JSON, you can use that to query your database.

From this approach, getting consistent JSON responses is quite challenging. Read more here:
[https://community.openai.com/t/getting-response-data-as-a-fixed-consistent-json-response/28471/8](https://community.openai.com/t/getting-response-data-as-a-fixed-consistent-json-response/28471/8)

**Comment by premtemp1** [comment]
Thanks, but similar to what you have done. How do you parse that json and
store it to pinecone.
Then can you use the similarity search to get the result (without.LLM).

 const data = await pineconeStore.similaritySearch(q, 5);

In your well written article. you use a text doc with splitter . However,
in my case each json object is a document.

Thanks

**Comment by fandyaditya** [comment]
I've never tried it before, but in theory, I think we can store the "textify" JSON object alongside with itself as a meta data

You're right, we don't need to split the JSON object. The JSON object itself that will become the document, the chunk.

Lets use your data as example:

```
[
  {
     "name :"rest 1"
     "type":"italian",
     "location":[
        "city":" some city"
        "zip" :"33333"
      ],
     " description":" some description"
     "menu":[
         menu item 1
         menu item 3
     ]
  },
  {
     "name :"rest 2"
     "type":"indian",
     "loacation":[
        "city":" some city"
        "zip" :"33333"
      ],
     " description":" some description"
     "menu":[
         menu item 1
         menu item 3
     ]
  }
.....
]
```
First we need to testify the JSON object, become something like this:

```
let txt = "Name 'rest1' 
type: 'Italian' 
location: 
 - city' : 'some city', 
 - zip: '3333', 
- description: Some Description, 
 menu: 
 - menu item 1,
 - menu item3
 "
```

Now create the document and store it:

```
let documents  = []
const document = new Document({
                pageContent: txt,
                metadata: {
                    the JSON object
                }
            });
            documents.push(document);
            
 PineconeStore.fromDocuments(documents, new OpenAIEmbeddings(), { pineconeIndex: pinecone.index('indexname'), namespace: 'namespacename' })
```

The key is to "textify" the JSON object so it can be read as natural language. The closer the better

**Comment by premtemp1** [comment]
Thanks you.
I will try it but the challenge is how to return the matching list (entire metadata). Once , we get the result then I can format and send the response back to the chat.
Thanks again for your help.

**Comment by fandyaditya** [comment]
Glad can help!
